### ISSUE TITLE
Call to undefined method Cissee\WebtreesExt\MoreI18N::plural()

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#115]
When using Vesta 2.1.17.0.0 or .0.1 - I'm not sure.

```
Call to undefined method Cissee\WebtreesExt\MoreI18N::plural() …/modules_v4/vesta_extended_relationships/UserRepositoryExt.php:77
#0 …/modules_v4/vesta_extended_relationships/ExtendedRelationshipModule.php(1154): Cissee\Webtrees\Module\ExtendedRelationships\UserRepositoryExt->usersLoggedInQuery()
#1 …/resources/views/tree-page-block.phtml(20): Cissee\Webtrees\Module\ExtendedRelationships\ExtendedRelationshipModule->getBlock()
```

**Comment by ric2016** [comment]
Fixed in release 2.1.17.0.2.

**Comment by hartenthaler** [comment]
It is still there in 2.1.17.0.2
```
Call to undefined method Cissee\WebtreesExt\MoreI18N::plural() …/modules_v4/vesta_extended_relationships/UserRepositoryExt.php:77
#0 …/modules_v4/vesta_extended_relationships/ExtendedRelationshipModule.php(1154): Cissee\Webtrees\Module\ExtendedRelationships\UserRepositoryExt->usersLoggedInQuery()
#1 …/resources/views/user-page-block.phtml(20): Cissee\Webtrees\Module\ExtendedRelationships\ExtendedRelationshipModule->getBlock()
#2 …/app/View.php(183): include('...')
```

**Comment by ric2016** [comment]
Missed a spot, see commit. Next Vesta release probably to fololw tomorrow.

**Comment by hartenthaler** [comment]
Vielen Dank!
