### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HRN65** [vesta-webtrees-2-custom-modules/vesta_extended_relationships#71]
Everything looks fine after upgrading to webtrees 2.0.23 and Extended Relationships 2.0.23+2.1.0-beta.2.0.0, but in website logs I find following error:

Cissee\Webtrees\Module\ExtendedRelationships\ExtendedRelationshipModule …/vendor/aura/router/src/Map.php:189 #0 …/app/Helpers/functions.php(166): Aura\Router\Map-&gt;getRoute() <b>#1 …/modules_v4/vesta_extended_relationships/ExtendedRelationshipModule.php(281): route()</b> <b>#2 …/modules_v4/vesta_extended_relationships/FunctionsPrintRels.php(103): Cissee\Webtrees\Module\ExtendedRelationships\ExtendedRelationshipModule::getRelationshipLink()</b> <b>#3 …/modules_v4/vesta_extended_relationships/FunctionsPrintRels.php(76): Cissee\Webtrees\Module\ExtendedRelationships\FunctionsPrintRels::printSlcasBetween()</b> <b>#4 …/modules_v4/vesta_extended_relationships/AjaxRequests.php(42): Cissee\Webtrees\Module\ExtendedRelationships\FunctionsPrintRels::printSlcas()</b> <b>#5 …/modules_v4/vesta_extended_relationships/ExtendedRelationshipModule_20.php(623): Cissee\Webtrees\Module\ExtendedRelationships\AjaxRequests::printFamilySlcas()</b> #6 …/app/Http/RequestHandlers/ModuleAction.php(88): Cissee\Webtrees\Module\ExtendedRelationships\ExtendedRelationshipModule_20-&gt;getFamRelsAction() #7 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction-&gt;handle() #8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler-&gt;process() #9 …/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher-&gt;handle() #10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule-&gt;process() #11 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher-&gt;handle() #12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf-&gt;process() #13 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle() #14 …/app/Http/Middleware/Router.php(166): Middleland\Dispatcher-&gt;dispatch() #15 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router-&gt;process() #16 …/app/Http/Middleware/BootModules.php(62): Middleland\Dispatcher-&gt;handle() #17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules-&gt;process() #18 …/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher-&gt;handle() #19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes-&gt;process() #20 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher-&gt;handle() #21 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}() #22 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection-&gt;transaction() #23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction-&gt;process() #24 …/app/Http/Middleware/DoHousekeeping.php(74): Middleland\Dispatcher-&gt;handle() #25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping-&gt;process() #26 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher-&gt;handle() #27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme-&gt;process() #28 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher-&gt;handle() #29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode-&gt;process() #30 …/app/Http/Middleware/UseLanguage.php(70): Middleland\Dispatcher-&gt;handle() #31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage-&gt;process() #32 …/app/Http/Middleware/UseSession.php(71): Middleland\Dispatcher-&gt;handle() #33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession-&gt;process() #34 …/app/Http/Middleware/UpdateDatabaseSchema.php(58): Middleland\Dispatcher-&gt;handle() #35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema-&gt;process() #36 …/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher-&gt;handle() #37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar-&gt;process() #38 …/app/Http/Middleware/UseDatabase.php(117): Middleland\Dispatcher-&gt;handle() #39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase-&gt;process() #40 …/app/Http/Middleware/BadBotBlocker.php(223): Middleland\Dispatcher-&gt;handle() #41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker-&gt;process() #42 …/app/Http/Middleware/CompressResponse.php(75): Middleland\Dispatcher-&gt;handle() #43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse-&gt;process() #44 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher-&gt;handle() #45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength-&gt;process() #46 …/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher-&gt;handle() #47 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp-&gt;process() #48 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp-&gt;process() #49 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher-&gt;handle() #50 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions-&gt;process() #51 …/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher-&gt;handle() #52 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl-&gt;process() #53 …/app/Http/Middleware/ReadConfigIni.php(69): Middleland\Dispatcher-&gt;handle() #54 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni-&gt;process() #55 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher-&gt;handle() #56 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders-&gt;process() #57 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher-&gt;handle() #58 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse-&gt;process() #59 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle() #60 …/app/Webtrees.php(241): Middleland\Dispatcher-&gt;dispatch() #61 …/app/Webtrees.php(228): Fisharebest\Webtrees\Webtrees::dispatch() #62 …/index.php(44): Fisharebest\Webtrees\Webtrees-&gt;httpRequest() #63 {main}

**Comment by HRN65** [comment]
Sorry. I see this has already been fixed.
Thank you
